### PR TITLE
Fixed #8 in submodlue metaschema-xslt to fix the cross-site linking

### LINKED ISSUE #8: Model reference pages failing to link between each other
A community member discovered that reference pages follow the format `OSCAL-Reference/models/v1.1.0/complete/json-outline/` but tend to link to other reference pages in the format `OSCAL-Reference/models/v1.1.0/complete/json-outline.html`.

This Hugo misconfiguration causes reference pages not to link to each other properly. Hugo's generated URLs need to be corrected (and aliased to both options).

To reproduce:
1. Visit https://pages.nist.gov/OSCAL-Reference/models/v1.1.0/complete/json-outline/
2. Click any of the model links.

### PR DESCRIPTION
**Pull request by JustKuzya**
Resubmitting the previously done and approved job

### CODE REVIEW

**Review by aj-stein-nist — APPROVED** [review]
I checked wendellpiez/metaschema-xslt and usnistgov/metaschema-xslt on the `develop` branch and everything lines up, modulo the PR I reviewed and merged with Dmitry. I am happy with this, but will leave for awareness, understanding, finally review by other team members before releasing.

**Comment by wendellpiez** [comment]
I will need to be instructed on whether and how this gets merged into the submodule source.

As for the patch itself, this might better be handled by adjusting `$reference-link` rather than mapping it in place. See https://github.com/usnistgov/metaschema-xslt/issues/59. This actually raises an interesting question of regression testing the Hugo build.

The bottom line is that link checking probably always needs to be run over generated files as presented, regardless.

**Comment by aj-stein-nist** [comment]
> I will need to be instructed on whether and how this gets merged into the submodule source.

The code was merged into metaschema-xslt, we are discussing this on the PR in OSCAL-Reference to push up the metaschema-xslt submodule in this repo.

> As for the patch itself, this might better be handled by adjusting `$reference-link` rather than mapping it in place. See [usnistgov/metaschema-xslt#59](https://github.com/usnistgov/metaschema-xslt/issues/59). This actually raises an interesting question of regression testing the Hugo build.

I reviewed the issue and understand the high-level relationship to the PR that was merged and we want to move up here, but is there something in particular we want to address in this submodule update?
 
> The bottom line is that link checking probably always needs to be run over generated files as presented, regardless.

Totally agreed. As a course of approving usnistgov/metaschema-xslt#57, I tested it by locally adjusting the submodule and trying several of the links (if one changed correctly, so do they all) before working with Dmitry to create this PR. Do you recommend any immediate changes or fixes in sprint? I don't disagree with your comments and circling back on it, but I am not sure you mean it has to happen now or later. Let us know.

**EDIT:** Sorry, I pointed to the wrong metaschema-xslt issue, not the actual PR Dmitry made.

**Comment by wendellpiez** [comment]
From what you say, all sounds good:

- The right thing is now being done for Hugo
- The correction is already in the upstream repo
- We can pick up the alignment with standalone production in https://github.com/usnistgov/metaschema-xslt/issues/59

How to maintain and regression test the Hugo-generation capability with the others (since links are one thing that commonly changes between deployments) is something we'll need to do with that Issue, which I will note in a comment.

**Comment by aj-stein-nist** [comment]
> From what you say, all sounds good:
> 
>     * The right thing is now being done for Hugo
> 
>     * The correction is already in the upstream repo
> 
>     * We can pick up the alignment with standalone production in [Test, adjust and plan refinements to standalone Docs production metaschema-xslt#59](https://github.com/usnistgov/metaschema-xslt/issues/59)
> 
> 
> How to maintain and regression test the Hugo-generation capability with the others (since links are one thing that commonly changes between deployments) is something we'll need to do with that Issue, which I will note in a comment.

Sounds good then, I merged the PR.

**Pull request merged**
